[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/sellernomics/golog"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/sellernomics/disclosure"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.6"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "2.1.0"
